/*******************************************************************************
 * File Name: project.h  
 * PSoC Creator 1.0 Production
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2010, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/
#include <cyfitter_cfg.h>
#include <cydevice.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <OE_aliases.h>
#include <OE.h>
#include <LE_aliases.h>
#include <LE.h>
#include <SCLK_aliases.h>
#include <SCLK.h>
#include <DATA_aliases.h>
#include <DATA.h>
#include <Counter_1.h>
#include <Clock_1.h>
#include <PRISM.h>
#include <Clock_2.h>
#include <MAGNET_aliases.h>
#include <MAGNET.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <cyPm.h>
#include <CySpc.h>
#include <cytypes.h>
#include <PSoC3_8051.h>

/*[]*/
